### ISSUE TITLE
getPossesiveSuffix / makePossesive with noun?

### ISSUE THREAD

**Issue by bonesoul** [CanPacis/affixi#3]
documentation mentions: 

`getPossesiveSuffix("Ayşe", Pronoun.SingularFirst, true) // Ayşe'm`

seems a documentation bug exists here as the related signature is;

`export declare const getPossesiveSuffix: (base: string, pronoun: Pronoun) => string;` 

which doesn't contain isProperNoun parameter.

Instead I tried the: 

`{makePossesive('Monako', Pronoun.SingularSecond, true)}`

which does handle the isProperNoun parameter but expected output is wrong:

- expected: Monako'nun
- actual output: Monako'n

Am I missing something here?

**Comment by canpacis** [comment]
Yes documentation was incorrect so I updated it, thank you. As for `{makePossesive('Monako', Pronoun.SingularSecond, true)} -> "Monako'n"` this is the expected behaviour, making it possesive as in 'Your Monako'. To get "Monako'nun" you need to use the `makeCompound` function with `Compound.Compounder` type. eg:

```typescript
makeCompound("Monako",  Compound.Compounder, true) // -> "Monako'nun"
```

**Comment by bonesoul** [comment]
thanks!
